#!/usr/bin/env bash
#
# Install NGINX on my server

NYANCAT='https://www.youtube.com/watch?v=QH2-TGUlwu4'
PATTERN='^\troot /var/www/html;$'
REPLACE="& \
rewrite ^/redirect_me ${NYANCAT} permanent; \
error_page 404 /custom_404.html; \
location = /custom_404.html { \
root /usr/share/nginx/html; \
internal; \
}"

apt-get -y update
apt-get -y install nginx

sed -i "s@${PATTERN}@${REPLACE}@" /etc/nginx/sites-available/default

echo 'Hello World!' > /var/www/html/index.html

echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

service nginx start

ufw allow 'Nginx HTTP'

