#!/usr/bin/env bash
#
# Install and configure HAProxy 1.5 on a new Ubuntu 16.04 server

apt-get -y update
apt-get -y install haproxy

cat >> /etc/haproxy/haproxy.cfg << EOF
backend web-backend
	balance roundrobin
	mode http
	server 1021-web-01 34.139.62.54:80 check
	server 1021-web-02 34.74.103.174:80 check
frontend web-frontend
	bind *:80
	mode http
	default_backend web-backend
EOF

service haproxy restart
