#!/usr/bin/env bash
#
#Print "Best School" 10 times but for 9th iteration, "Hi" on the new line using until loop

i=0
while ((i++ < 10))
do
	echo "Best School"
	if ((i == 9))
	then
		echo "Hi"
	fi
done
