#!/usr/bin/env bash
#
#Print "Best School" but for 4th iteration, print "bad luck" and for 8th print "good luck" using while loop

i=0
while ((i++ < 10))
do
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
